const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    // CHANGED: dropped responseSchema entirely — it was corrupting output on this nested structure.
    // Relying purely on strict prompt instructions instead, which is more reliable for complex shapes.
    const prompt = `You are an interview preparation assistant. Analyze the candidate below and respond with ONLY a single valid JSON object — no markdown code fences, no array wrapper, no commentary before or after — that EXACTLY matches this shape and these field names:

{
  "title": "string, the job title from the job description",
  "matchScore": number between 0 and 100,
  "technicalQuestions": [ { "question": "string", "intention": "string", "answer": "string" } ] (exactly 5 items),
  "behavioralQuestions": [ { "question": "string", "intention": "string", "answer": "string" } ] (exactly 5 items),
  "skillGaps": [ { "skill": "string", "severity": "low" or "medium" or "high" } ] (up to 5 items),
  "preparationPlan": [ { "day": number, "focus": "string", "tasks": ["string"] } ] (exactly 5 days)
}

Keep every "answer" and each task under 2 sentences so the JSON stays compact. Do not rename any field. Do not add fields not listed above. Return raw JSON only, starting with { and ending with }.

Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}
`

    const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json", // CHANGED: kept, but no responseSchema now
            maxOutputTokens: 8192,
        }
    })

    console.log("AI raw response:", response.text)
    console.log("Finish reason:", response.candidates?.[0]?.finishReason)

    let rawText = response.text.trim()

    // ADDED: strip markdown fences if the model adds them despite instructions
    if (rawText.startsWith("```")) {
        rawText = rawText.replace(/^```(json)?/, "").replace(/```$/, "").trim()
    }

    let parsed
    try {
        parsed = JSON.parse(rawText)
    } catch (err) {
        console.log("JSON parse failed on:", rawText) // ADDED: so we can see exactly what broke, if it ever does again
        throw new Error("AI returned invalid JSON")
    }

    if (Array.isArray(parsed)) {
        parsed = parsed[0]
    }

    return parsed

}



async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    // CHANGED: dropped responseSchema here too, for consistency and reliability
    const prompt = `Generate a resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        Respond with ONLY a single valid JSON object — no markdown fences, no commentary — in exactly this shape:
                        { "html": "string containing the full HTML content of the resume" }

                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content should not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        You can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            maxOutputTokens: 8192,
        }
    })

    let rawText = response.text.trim()
    if (rawText.startsWith("```")) {
        rawText = rawText.replace(/^```(json)?/, "").replace(/```$/, "").trim()
    }

    const jsonContent = JSON.parse(rawText)

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }